version: "3.1"

services: 
    app: 
        image: 
            strapi/strapi:3.1.3-alpine
        restart: unless-stopped
        volumes:
            - .:/srv/app
        environment: 
            DATABASE_CLIENT: mongo
            DATABASE_HOST: mongo
            DATABASE_NAME: db
            DATABASE_USERNAME: root
            DATABASE_PASSWORD: password
        ports: 
            - 1337:1337
        links:
            - mongo
        depends_on: 
            - mongo
    mongo: 
        image:
            mongo
        restart: unless-stopped
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password